service: example-app
frameworkVersion: ">=1.1.0 <2.0.0"
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

functions:
  app:
    handler: serverless.handler
    events:
      - http:
          path: /{any+}
          method: any
          cors: true
